### ISSUE TITLE
Firmware update UPS has stopped working

### ISSUE THREAD

**Issue by ociekly** [geeekpi/upsv3#14]
Hello.
I had to update the firmware because my motherboard suffered from turning off after about 24 hours. For this purpose, I purchased the NU-Link programmer. I made the updates today according to the PDF instructions. Everything ended correctly

The system does not seem to be working. There is no reaction after installing the batteries. I press the switch, the charge indicator shows for a moment that the batteries are fully charged, but the power to the Raspberry is not turned on (the RPI POWER LED is off). Repeated presses also activate the indicator. Holding the key down also activates the indicator momentarily. After connecting the charger, the status indicator "fills up" and only the last LED flashes (batteries full). I tried to program the system for a few hours, but without success. Is the firmware file correct?

![image](https://user-images.githubusercontent.com/46086374/157849136-3b6f9c44-200a-4f1e-90d1-86c589271ad3.png)

David

**Comment by ociekly** [comment]
what should be the bit configuration?
I seem to be using a newer version of the program.
![chipsettings](https://user-images.githubusercontent.com/46086374/171414760-19d5d912-da84-4d0a-8297-e089ec80c526.png)

**Comment by yoyojacky** [comment]
There is something wrong with your firmware. we do not recommend you update the firmware by yourself.

**Comment by SplavSlav** [comment]
I have exactly the same problem as ociekly. How to fix it?

**Comment by yoyojacky** [comment]
> 我遇到了与 ociekly 完全相同的问题。如何解决？

联系销售，提供你的order number，申请售后。
