### ISSUE TITLE
RTC and Low voltage auto shutdown

### ISSUE THREAD

**Issue by buncopter** [geeekpi/upsv3#3]
Hi, 

1) We don't know anything about the RTC. Can you please provide code to program it for date and time?

2) Can you please provide a script for auto shutdown (software) when low power?

For example, the X728 (competing UPS hardware) already have extensive software writeup to use the new hardware for software voltage-based shutdown, programming of RTC module, battery voltage and percentage reading, AC power loss detection etc. Just wondering if we can have something similar for the UPS V3?
https://github.com/geekworm-com/x728/blob/master/x728.sh
https://raspberrypiwiki.com/index.php?title=X728-Software&mobileaction=toggle_view_desktop

Thanks! Hardware is all there, just need the software side of things

**Comment by serantes** [comment]
I have the same problems and If you can't detect power shutdown this hardware is a waste of money. I tried the sample code with power up and power down and results are similar.

**Comment by yoyojacky** [comment]
Please try this :https://wiki.52pi.com/index.php/UPS_Plus_SKU:_EP-0136
