### ISSUE TITLE
bad hardware

### ISSUE THREAD

**Issue by Kels316** [geeekpi/upsv3#4]
I bought one of these to test for a project where we need 15 UPS for raspberry pi 4s. It lasted about 2hrs before it stopped working. Wont supply more than 1.6v to the pi when it's connected up, but 5.2v at the pins with the pi disconnected. Going off the lack of response to other issues raised here I'd say not worth the time and money.

**Comment by ThorstenS-linux** [comment]
I cannot confirm this. My board has already withstood various charging cycles. rtc and status queries work perfectly. 
For me the best raspi ups-board, even if it is not perfect.

**I miss:**
* complete shutdown of ups board, when raspi shuts down
* shutdown script, when button pressed
* restart pi, when power comes back after empty batteries
* a variant with 4x18650s ;-)
