### ISSUE TITLE
Is it possible to turn off the UPS board with `shutdown now`

### ISSUE THREAD

**Issue by adricen** [geeekpi/upsv3#5]
Hello,

I was wondering if it was possible to add a turn off function with I2C to the UPS board when calling `shutdown now` or something similar on a terminal.

Is it possible that UPS board will be connect to this *signal*  turn off and be on again pushing the on button ?

Thanks for all the work :clap:

**Comment by jpcwilliams** [comment]
Would also love this as a feature. Currently after shutting down you then have to hold the power button to fully shut off and then click again to reboot which is a bit of a pain

**Comment by yoyojacky** [comment]
sorry, this version can not do that , please try this : https://wiki.52pi.com/index.php/UPS_Plus_SKU:_EP-0136
